[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
rayon = "1.10.0"
regex = "1.11.1"

[[bin]]
name = "day1"

[[bin]]
name = "day2"

[[bin]]
name = "day3"

[[bin]]
name = "day3_nom"
